# Generated by Django 5.0.3 on 2024-05-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskysection',
            name='section_video_url',
            field=models.URLField(null=True),
        ),
    ]
