# Generated by Django 5.0.3 on 2024-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_riskysection_section_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskysection',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
