version: "3"

services:
  db:
    image: mysql
    container_name: gamst_db
    volumes:
      - ./volume:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: qweiop123
      MYSQL_DATABASE: gamst
    ports:
      - "3306:3306"
    networks:
      - gamst-network

networks:
  gamst-network:
    name: gamst-network
    driver: bridge