# Generated by Django 5.0.3 on 2024-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_caption_updated_at_caption_sentiment_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='detected_object',
        ),
        migrations.RemoveField(
            model_name='caption',
            name='sentence',
        ),
        migrations.AddField(
            model_name='caption',
            name='cropped_sentence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='caption',
            name='original_sentence',
            field=models.TextField(null=True),
        ),
    ]
