# Generated by Django 5.0.3 on 2024-04-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_riskysection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caption',
            old_name='cropped_sentence',
            new_name='sentence',
        ),
        migrations.RenameField(
            model_name='caption',
            old_name='original_sentence',
            new_name='sentiment_score',
        ),
    ]
