# Generated by Django 5.0.3 on 2024-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_riskysection_video_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskysection',
            name='clip_url',
            field=models.URLField(null=True),
        ),
    ]
